### ISSUE TITLE
Error downloading balances

### ISSUE THREAD

**Issue by devinellis** [monarchmoney/mint-export-extension#13]
Popup displays "Sorry, there was an error downloading your balances. Please try again."

Extension console log:
```
Received message with action: POPUP_OPENED
Received message with action: DOWNLOAD_ALL_ACCOUNT_BALANCES
TypeError: Cannot destructure property 'balancesByDate' of '(intermediate value)' as it is undefined.
    at Ui (chrome-extension://doknkjpaacjheilodaibfpimamfgfhap/assets/js/Popup.762c3a5f.js:3:726)
    at async chrome-extension://doknkjpaacjheilodaibfpimamfgfhap/assets/js/Popup.762c3a5f.js:3:1635
    at async Promise.all (index 3)
    at async Qi (chrome-extension://doknkjpaacjheilodaibfpimamfgfhap/assets/js/Popup.762c3a5f.js:3:1559)
    at async te (chrome-extension://doknkjpaacjheilodaibfpimamfgfhap/src/pages/background/index.js:14:101543)
```

Latest Chrome (119.0.6045.124) and no other extensions installed. Downloading transactions worked perfectly.

**Comment by oaosman84** [comment]
Thanks!! Should be fixed by https://github.com/monarchmoney/mint-export-extension/pull/9 (pending new Chrome Store release approval)

**Comment by devinellis** [comment]
Confirmed this bug does not persist in 1.0.3, but I ran into the rate limiting from https://github.com/monarchmoney/mint-export-extension/issues/15
